### ISSUE TITLE
Focal point for crop coordinates

### ISSUE THREAD

**Issue by lmartins** [MINDKomm/Timmy#1]
Hi,

This looks like a very, very useful addition to Timber.
One thing I've struggling with Timber's images is a way to better control cropping. With standard WordPress images, you can use something like https://wordpress.org/plugins/my-eyes-are-up-here/ which is absolutely brilliant for that. Unfortunately this doesn't work for Timber's arbitrary cropping sizes. Do you have any plans for something similar?

**Comment by lgaechter** [comment]
Thanks, Luis!

I totally see your point. We sometimes struggle with this, too. What we have found to be working quite well is assigning multiple images to a post for different purposes: An image to be used as a thumbnail or a post preview, an image to be used as a header image and so on. Or even different images for art direction for different screen sizes. So we don’t just use Post Thumbnails, but create more image fields for a post with [Advanced Custom Fields](http://advancedcustomfields.com/).

Timmy just passes configuration values from the `resize` option down to Timber’s `TimberImageHelper` class. In the `resize` option you use the same options as in Timber’s [resize filter](https://github.com/jarednova/timber/wiki/TimberImage#resize). That’s why I think this issue would be more of an issue for Timber than an issue for Timmy. I saw that you have already asked the same question over at https://github.com/jarednova/timber/issues/772.

However, maybe it’s possible to connect image sizes defined through Timmy with WordPress images even more than they currently are. It would be nice if more image plugins would just work with Timber, without having to add every nice functionality to Timber separately. I’ll probably have a look into that soon.

**Comment by lmartins** [comment]
Than you so much for your input here Lukas. I was already suspecting that would be the case, but it is always nice to ear the opinion from someone else, so thanks.
I see that you tagged the issue with **enhancement**, should I close this?

**Comment by lgaechter** [comment]
Yes, I guess it can be closed for now.
