### ISSUE TITLE
Outdated example in documentation?

### ISSUE THREAD

**Issue by patrickcameron** [mindkomm/timmy#19]
Hi, just flagging a very minor possible issue in the documentation.

On line 200 of /docs/image-configuration.md the example includes `'resize_srcset' => true` - is this an outdated name for the `generate_srcset_sizes` option?

**Comment by gchtr** [comment]
Hey @patrickcameron 

I couldn’t find any setting named `resize_srcset` in earlier versions of Timmy 🙈. So I don’t know where that came from. I probably meant to use `generate_srcset_sizes` in the example.

Thanks for mentioning this 👍. Fixed in 695116850e8879c3fefd10f08953d5892783f78e.
