### ISSUE TITLE
Thumbnail not recognised and Unknown "get_timber_image_responsive"

### ISSUE THREAD

**Issue by lmartins** [MINDKomm/Timmy#2]
I followed the steps mentioned in the readme file, namely I installed Timber and Timmy, reset every image size to 0 in Media Settings and placed the following on my functions file:
```php

// We are resetting default image sizes so that we can override them with a
// Timmy, a more convenient way to work with images and Timber
set_post_thumbnail_size(0, 0);

function gwm_remove_default_image_sizes( $sizes) {
    unset( $sizes['shop_thumbnail']);
    unset( $sizes['shop_catalog']);
    unset( $sizes['shop_single']);
    return $sizes;
}
add_filter('intermediate_image_sizes_advanced', 'gwm_remove_default_image_sizes');


// Set the new images sizes to be used in twig templates
function get_image_sizes() {
    return array(
        'thumbnail' => array(
            'resize' => array( 150, 150 ),
            'name' => 'Thumbnail',
            'post_types' => array( 'all' ),
        ),
        'custom-4' => array(
            'resize' => array( 370 ),
            'srcset' => array( 2 ),
            'size' => '(min-width: 992px) 33.333vw, 100vw',
            'name' => 'Width 1/4 fix',
            'post_types' => array( 'post', 'page', 'product' ),
        ),
    );
}
```
However when I go to the media center in the Dashboard, WordPress is loading the full size of the images as thumbnails, which makes me believe it isn't running the above function. Do I need to hook it up to any WordPress action?

In the front-end, im also getting the following errors:
```
Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unknown "get_timber_image_responsive" filter in "products/parts/product-tile.html" at line 18.' in /Users/luismartins/Sites/project.dev/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php on line 601
```
and
```
Twig_Error_Syntax: Unknown "get_timber_image_responsive" filter in "products/parts/product-tile.html" at line 18. in /Users/luismartins/Sites/hydracheck.dev/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php on line 601
```

which lead me to believe Timmy isn't being recognised at all. Am I missing some step?

**Comment by gchtr** [comment]
From what I can see the configuration looks good. It’s actually not essential to set all WordPress sizes to `0`, it just tells WordPress to not use any of its own sizes.

There’s no need to hook it up to any action or filter. However, Timmy uses `timber_context` and `get_twig` filters to set filters and functions which can be used in the template files. Do you have any functions of your own that hook into these filters?

I get the same errors as you when I deactivate Timmy. Did you make sure it’s activated?

**Comment by lmartins** [comment]
I do have a function hooked into `timber_context` but nothing associated with `get_twig`. I tried commenting my own call to `timber_context` but it made no difference.
I've also confirmed that `Timmy` returns true when I run `class_exists('Timmy')` in my code, which makes it all more strange.

**Comment by gchtr** [comment]
Any other plugins that might interfere? I would try the standard procedure of deactivating plugin by plugin to see whether one of it might cause trouble.

The other thing I could think of is that Timmy is somehow loaded before Timber. Could you try and wrap the plugin init call in https://github.com/MINDKomm/Timmy/blob/master/timmy.php#L312 with a `plugins_loaded` action? Like this:

```php
add_action( 'plugins_loaded', function() {
	new Timmy();
});
```

**Comment by lmartins** [comment]
This is site im just starting working on, the only plugins I have are Timber, Timmy and WooCommerce. I've tested wrapping the init call as you suggest and as soon as I did that it started working normally.

**Comment by gchtr** [comment]
Thanks for helping to find the source of this issue! I guess since you already put that lines into your code, it’s no use to download the latest master again ;). I hope you can get to work now.

**Comment by lmartins** [comment]
Yes, im now exploring the library. Thank you for the help =)
