### ISSUE TITLE
Timmy stopped working after Upgrade

### ISSUE THREAD

**Issue by jawittdesigns** [mindkomm/timmy#22]
On a project I'm working on we recently upgraded Timmy from 0.13.6 to 0.14.0 and Timmy stopped working all together as far as I can tell.

We have installed:
timber/timber: 1.1
mindkomm/timmy: 0.14.0
kint-php/kint-twig: 2.0

Are there any known issues with these packages?

**Comment by gchtr** [comment]
The 0.14.0 release brought some updates for how Timmy handles image meta data. Can you try running [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) and see if that solves the issue?

**Comment by gchtr** [comment]
I’m going to close this issue. If you still have problems with the most current version of Timmy and can provide more info about what exactly is broken, then I can still reopen this issue and look at it in more detail.
