### ISSUE TITLE
Uninitialized string offset: 0 error

### ISSUE THREAD

**Issue by flowen** [mindkomm/timmy#27]
I copied some code from an old project with timmy (which works perfect, thanks so much for this great package!). But in a new project it's giving me this (non-descriptive) error an dI'm not sure what the cause of it could be:

```Notice: Uninitialized string offset: 0 in /Users/flowflow/_DATA/DOCUMENTS/_htdocs/_MAMP_htdocs/guildconferences.com/wp-content/plugins/timmy-0.14.1/lib/Helper.php on line 110```

Any pointers?

**Comment by flowen** [comment]
I fixed it by removing unused image-sizes. Not sure why they would produce this error

**Comment by gchtr** [comment]
Hey @flowen, I’m glad you could fix it so quickly 👍.

It seems like the error appears if you had an image configuration entry without having `resize` defined or with an empty `resize` entry.

**Comment by flowen** [comment]
yea the resize was '' 
strangely though, worked without errors on the other project
