### ISSUE TITLE
"sizes" attribute set even when no "srcset" is availible, violating w3 check

### ISSUE THREAD

**Issue by RastaTux** [mindkomm/timmy#32]
Hey!
We are getting an error from w3 validator when using timmy, because we have just one size but no srcset. Could you add a check how many sizes are in the array and if necessary, change the attribute to "size"? This should fix the issue, iirc.

**Comment by gchtr** [comment]
> if necessary, change the attribute to "size"

@RastaTux You mean using `src` and omitting the `size` and `srcset` attributes? Could you make a quick HTML code example for a snippet that is flagged by the validator and one that wouldn’t be?

**Comment by RastaTux** [comment]
`<img sizes="240px" src="https://xxxxxx.com/image.jpg">`
-> Error: The sizes attribute may be specified only if the srcset attribute is also present.
If only one image is in the sizes array:
`<img src="https://xxxxxx.com/image.jpg">`

**Comment by gchtr** [comment]
This should be fixed with the [0.14.5 release](https://github.com/mindkomm/timmy/releases/tag/0.14.5).
