### ISSUE TITLE
Support wordpress loading="lazy" feature (since 5.5)

### ISSUE THREAD

**Issue by sque89** [mindkomm/timmy#35]
We updated our wordpress recently to 5.5 mainly because we want to make use of the lazy loading attribute which wordpress can now add automatically.

I know Timmy supports lazy loading with JS, but is it planned to support the browser native loading attribute?

Thanks a lot!

**Comment by gchtr** [comment]
Yes, this is on top the list!

**Comment by gchtr** [comment]
Lazy loading is supported in the new version of Timmy. I just released a first beta for Timmy v1.0.0: https://github.com/mindkomm/timmy/releases/tag/1.0.0-beta.1.

Check out the updated [Lazy Loading Guide](https://github.com/mindkomm/timmy/blob/1.x/docs/lazy-loading.md).
