### ISSUE TITLE
resize to height not generating images

### ISSUE THREAD

**Issue by koraysels** [MINDKomm/Timmy#4]
Hi, if i do this:

```
'srcset'     => array(
                2,
                array(0, 300),
                array(0, 600),
                array(0, 400),
                array(0, 800),
                array(0, 750),
                array(0, 1500)
            ),
```

It does not work, in timber if i use the resize filter it does work..

**Comment by gchtr** [comment]
Hi Koray

I didn’t use a width value of `0` before, so I honestly have to say that I didn’t know this works in Timber 😁. The reason it didn’t work in Timmy was that for the responsive image markup, we need to know the width at which the image will be displayed. With a width of `0`, the markup was like this:

```html
<img srcset="image-0x600-c-default.jpg 0w, image-0x800-c-default.jpg 0w">
```
This resulted in an error in Picturefill for me. Of course the browser wouldn’t display the image if the markup says it has no width 😉.

But now it should work. When you download the latest version, you should be good to go.

How does Timmy work for you? Do you get along? Could you delete all image sizes you don’t need?
