### ISSUE TITLE
Content images from Gutenberg are not always detected due to wrong regex

### ISSUE THREAD

**Issue by alexej-d** [mindkomm/timmy#40]
Hi, responsive content images are not always working. I identified the regex on [this line](https://github.com/mindkomm/timmy/blob/master/lib/Responsive_Content_Images.php#L100) as the culprit as it ignores Gutenberg images when the figure has a class name attribute like this `wp-block-image alignfull size-large`.

**Comment by gchtr** [comment]
Hey @alexej-d

Yes, that issue was already identified and I almost have a fix finished. I hope to be able to release a version with the fix soon.

Thanks for digging into the code and search for the culprit.

**Comment by alexej-d** [comment]
Great! Thanks for the quick support!

**Comment by gchtr** [comment]
This should now be fixed with the [0.14.8 release](https://github.com/mindkomm/timmy/releases/tag/0.14.8).
