### ISSUE TITLE
lazy_src in picture_responsive

### ISSUE THREAD

**Issue by jbjanot** [mindkomm/timmy#50]
Hi!
Thanks for this super nice project.
I'm currently thinking of updating my current project to make use of timmy in version 1.0.0 beta 2 (I absolutely want to take advantage of webp and the picture format).
I am using a JS lib and I ran into an issue with the lazy parameters : the parameters to force prepend data- to the various attributes does not seem to work in the context of the picture_responsive (lazy_srcset: true, lazy_src: true, lazy_sizes: true).

Is this something you could take care of?

Thanks a lot for your help and for this hard work, it really is a nice addition to Timber.

Have a nice day!

**Comment by gchtr** [comment]
Hey @jbjanot. This should now work in the latest beta release: https://github.com/mindkomm/timmy/releases/tag/1.0.0-beta.3.
