### ISSUE TITLE
Compatibility with Composer-installed Timber

### ISSUE THREAD

**Issue by elivz** [MINDKomm/Timmy#6]
Now that [Timber is recommending installation via Composer](https://github.com/timber/timber/blob/master/README.md#installation), it would be great if we could also install Timmy that way. Or, if that is not possible for some reason, if Timmy were at least compatible with Timber installed via Composer. 

Right now, with Timber installed via Composer and Timmy installed as a WP plugin, I get the following error:

    Fatal error: Uncaught Twig_Error_Syntax: Unknown "get_timber_image_responsive" filter in "page.twig" at line 6. in /var/www/wp-content/themes/themename/vendor/twig/twig/lib/Twig/ExpressionParser.php on line 605

It looks like with this configuration, Timber parses the templates before Timmy has hooked in its custom filters. I'll keep installing Timber as a plugin for the time being (Timmy is just too good to give up), but I do like the idea of keeping them as dependencies of the theme, rather than installed plugins, since they are really only useful & necessary for the particular theme I am using them on.

Thanks for considering!

**Comment by gchtr** [comment]
That’s a very good idea and I think it should be possible to make it work both as a plugin and with Timber installed with Composer. That would also make it easier for people to update. I will definitely look into this.

You are right. Timmy is loaded inside the `plugins_loaded` filter, which only works when Timber is also installed as a plugin. Up until now I didn’t know that I don’t have to install Timber as a plugin, and what it would mean to install it with Composer. It would definitely have to be compatible with the different locations people keep their dependencies in. According to https://github.com/timber/timber/blob/master/bin/timber.php, Timber first looks in the folder itself, then in wp_content, then in the plugin dir and then in the possible theme dirs. That tells me that Timmy will have to account for that, too.

**How do *you* install Timber?** Do you install it as a dependency right inside your theme? Or do you keep it elsewhere so you can better access it from your self-written plugins (if you have any), too?

Oh, and it’s very nice to hear that Timmy is just to good to give up. Yay 😄, thanks! We didn’t get much feedback yet 😉.

**Comment by elivz** [comment]
I've only used Timmy on one project so far (although I am about to start a second one). It was great...so much better than the weird native image sizing. I primarily work with [Craft](https://craftcms.com), which lets you generate arbitrarily-sized images on the fly in the templates, so it was always painful going back to WordPress and having to pre-define my sizes & run Regenerate Thumbnails every time I needed a new size.

I think you are right that you will need to check all those locations for the Timber library. As an experiment, I just pasted the autoload code from that `Timber.php` file into the top of `timmy.php`, and everything seems to work properly now! Much easier than I expected.

Ideally, it would still be nice to have to option to installed Timmy as a dependency from my theme's `composer.json`, but getting it working again was my main priority. I install Timber into /wp-content/themes/mytheme/vendor, but I imagine you would want to support the same list of potential locations as Timber does.

**Comment by gchtr** [comment]
Totally. I feel that, too. If you have lots of images and different sizes you work with, native WordPress image handling can be a real hassle. I heard that Craft has arbitrarily-sized images implemented. Lucky you!

I think I might have found an easier way to make it work, see https://github.com/MINDKomm/Timmy/releases/tag/0.10.1

Timmy is now on packagist. You can require it through

```
composer require mindkomm/timmy
```
Because I added Timber as a dependency of Timmy, you won’t have to install Timber separately. And no need to check for all the autoload locations, if you required the `autoload.php` in your theme functions file.

You can still use Timmy as a plugin if you prefer installing Timber as a plugin. So it should work ways, yippee!

Happy to hear your feedback.

**Comment by elivz** [comment]
Awesome! I will give it a try tomorrow and let you know if I have any problems.
