### ISSUE TITLE
deprecation: PHP 8.1: FILTER_SANITIZE_STRING

### ISSUE THREAD

**Issue by drzraf** [mindkomm/timmy#65]
`<b>Deprecated</b>:  Constant FILTER_SANITIZE_STRING is deprecated in <b>/vendor/mindkomm/timmy/lib/Timmy.php</b> on line <b>441</b><br />`

**Comment by gchtr** [comment]
Should be fixed in https://github.com/mindkomm/timmy/releases/tag/v1.1.0.
