### ISSUE TITLE
Inline Styles

### ISSUE THREAD

**Issue by philJohnson** [MINDKomm/timmy#7]
Is it possible to remove the inline style that gets added for width?

**Comment by gchtr** [comment]
Yes it is, with the [oversize parameter](https://github.com/MINDKomm/timmy#oversize).

I saw that the documentation wasn’t up date for `oversize` and tried to make it more clear what options you have.

**Comment by philJohnson** [comment]
I've looked at the documentation and it's not working. Ideally I want to be able to have 
```
'oversize' => array(
    'allow' => false,
    'style_attr' => false,
),
```
It doesn't appear to work though.

looking at 'lib/Timmy.php' line 360 should probably read

`if ( ! $oversize['allow'] && $oversize['style_attr']) {`

otherwise `$restrict` will be set based on height or width and include inline styles

**Comment by gchtr** [comment]
Ok, I see. Thanks for pointing that out!
Could you check with the latest master version to see if it is working?
